---
platform: linux

image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
    
inputs:
  - name: kissj-app
outputs:
  - name: image
      
run:
  path: build
