apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-caddy
  labels:
    app.kubernetes.io/name: {{ .Chart.Name}}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: webserver
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.caddy.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: webserver
  template:
    metadata:
      labels:
        app.kubernetes.io/component: webserver
    spec:
      containers:
      - name: caddy
        image: {{ .Values.caddy.image.name }}:{{ .Values.caddy.image.tag}}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 30
          terminationGracePeriodSeconds: 60
        
        env:
          #Define the environment variable
          - name: PHPFPM_HOST
            value: {{ .Release.Name}}-php-fpm
          - name: WEB_HOST
            value: {{ .Values.app.url }}
        ports:
        - containerPort: 80
        - containerPort: 9253
        - containerPort: 8000

        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        volumeMounts:
        - mountPath: /etc/caddy
          name: {{ .Release.Name}}-caddy-config
      volumes:
      - name: {{ .Release.Name }}-caddy-config
        configMap:
          name: {{ .Release.Name }}-caddy-config
